version: '3.4'

services:
  catalogdb2:
    image: mongo

  catalog.api2:
    image: ${DOCKER_REGISTRY-}catalogapi2
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  mongo_data:
