version: '3.4'

services:
  catalogdb2:
    container_name: catalogdb2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api2:
    container_name: catalog.api2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb2:27017"
    depends_on:
      - catalogdb2
    ports:
      - "8000:80"
